# Generated by Django 3.0.6 on 2021-06-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Category', models.CharField(default='Thriller', max_length=50)),
                ('Directed_by', models.CharField(max_length=20)),
                ('Produced_by', models.CharField(max_length=20)),
                ('Written_by', models.CharField(max_length=20)),
                ('Thumbnail', models.ImageField(upload_to='ticketapp/images')),
                ('Price', models.FloatField()),
                ('promo', models.URLField()),
                ('loc', models.ManyToManyField(to='ticketapp.Halls')),
            ],
        ),
    ]
