# Generated by Django 3.0.6 on 2021-06-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='promo',
        ),
    ]
