# Generated by Django 3.0.6 on 2021-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_movie_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='contact',
            field=models.CharField(default='No contact available', max_length=12),
        ),
        migrations.AddField(
            model_name='halls',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='halls',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
