# Generated by Django 3.0.6 on 2021-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20210620_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='photo',
            field=models.ImageField(default='No image available', upload_to='ticketapp/images'),
        ),
        migrations.AddField(
            model_name='halls',
            name='url',
            field=models.URLField(default='No location available', max_length=500),
        ),
    ]
